// Intentional public boundary for the pure Presentation Core. Renderers may
// consume these contracts, but the Core imports neither renderers nor UI.
export { ANIMATION_CAPABILITIES } from "./capabilities/animation";
export { TRANSITION_CAPABILITIES } from "./capabilities/transition";
export {
  alignElementsToCanvas,
  alignElementsToReference,
  bringForward,
  bringToFront,
  configureAnimation,
  configureTransition,
  confirmPresentationPublished,
  confirmPresentationSaved,
  createElement,
  createElements,
  createPresentation,
  createPresentationDeletionIntent,
  createSlide,
  deleteElement,
  deleteElements,
  deleteSlide,
  distributeElements,
  duplicateElement,
  duplicateSlide,
  editElement,
  editElements,
  editSlide,
  moveElement,
  moveElements,
  redo,
  redoPresentation,
  redoSlide,
  renamePresentation,
  reorderElement,
  reorderSlide,
  replaceAsset,
  resizeElement,
  rotateElements,
  sendBackward,
  sendToBack,
  setElementsOpacity,
  undo,
  undoPresentation,
  undoSlide,
} from "./commands";
export { isHistoryEntryApplicableToSlide } from "./history";
export type {
  PresentationFontAsset,
  PresentationFontDefinition,
  PresentationFontId,
} from "./presentation-font-catalog";
export {
  getPresentationFontDefinition,
  getPresentationFontStack,
  PRESENTATION_FONT_CATALOG,
  PRESENTATION_FONT_IDS,
} from "./presentation-font-catalog";
export {
  deserializePresentationState,
  isPresentationOperationCompatibleWithState,
  serializePresentationState,
} from "./serialization";
export type {
  AlignElementsToCanvasInput,
  AlignElementsToReferenceInput,
  AnimationCapability,
  AnimationCategory,
  AnimationConfiguration,
  AnimationConfigurationInput,
  AnimationType,
  BringForwardInput,
  BringToFrontInput,
  CommandResult,
  ConfigureAnimationInput,
  ConfigureTransitionInput,
  ConfirmPresentationPublishedInput,
  ConfirmPresentationSavedInput,
  CreateElementInput,
  CreateElementsInput,
  CreatePresentationDeletionIntentResult,
  CreatePresentationInput,
  CreatePresentationResult,
  CreateSlideInput,
  DeleteElementInput,
  DeleteSlideInput,
  DeserializePresentationStateOptions,
  DeserializePresentationStateResult,
  DistributeElementsInput,
  DuplicateElementInput,
  DuplicateSlideInput,
  EditElementInput,
  EditElementsInput,
  EditSlideInput,
  ElementAlignment,
  ElementPatch,
  ElementPosition,
  ElementSize,
  EntityRevisionTransition,
  HistoryCommandInput,
  ImageElement,
  ImageStyle,
  ImageStylePatch,
  MoveElementInput,
  MoveElementsInput,
  NewPresentationElement,
  OperationSource,
  PresentationCanvas,
  PresentationCoreError,
  PresentationCoreErrorCode,
  PresentationDeletionIntent,
  PresentationDocumentState,
  PresentationElement,
  PresentationLifecycle,
  PresentationOperation,
  PresentationSnapshotIntegrityStatus,
  PresentationSnapshotReceiptVerificationInput,
  PresentationState,
  PresentationStatus,
  RenamePresentationInput,
  ReorderElementInput,
  ReorderSlideInput,
  ReplaceAssetInput,
  ResizeElementInput,
  RotateElementsInput,
  ScopedHistory,
  SendBackwardInput,
  SendToBackInput,
  SerializePresentationStateResult,
  SetElementsOpacityInput,
  ShapeElement,
  ShapeStyle,
  ShapeStylePatch,
  ShapeType,
  Slide,
  SlideBackground,
  SlidePatch,
  SlideTransition,
  TextAlignment,
  TextElement,
  TextFontFamily,
  TextFontWeight,
  TextStyle,
  TextStylePatch,
  TransitionCapability,
  TransitionConfigurationInput,
  TransitionType,
  VerifyPresentationSnapshotReceipt,
} from "./types";
export {
  PRESENTATION_CANVAS,
  TEXT_ALIGNMENTS,
  TEXT_FONT_FAMILIES,
  TEXT_FONT_WEIGHTS,
} from "./types";
export {
  isTextAlignment,
  isTextFontFamily,
  isTextFontWeight,
  isValidPresentationId,
  isValidPresentationRevision,
  isValidPublicId,
  isValidSlideBackground,
  isValidTimestamp,
  isValidTitle,
} from "./validation";
