// Intentional public boundary for the pure Presentation Core. Renderers may
// consume these contracts, but the Core imports neither renderers nor UI.
export { ANIMATION_CAPABILITIES } from "./capabilities/animation";
export { TRANSITION_CAPABILITIES } from "./capabilities/transition";
export {
  bringForward,
  configureAnimation,
  configureTransition,
  confirmPresentationPublished,
  confirmPresentationSaved,
  createElement,
  createPresentation,
  createPresentationDeletionIntent,
  createSlide,
  deleteElement,
  deleteSlide,
  duplicateElement,
  duplicateSlide,
  editElement,
  editSlide,
  moveElement,
  redo,
  renamePresentation,
  reorderElement,
  reorderSlide,
  replaceAsset,
  resizeElement,
  sendBackward,
  undo,
} from "./commands";
export {
  deserializePresentationState,
  isPresentationOperationCompatibleWithState,
  serializePresentationState,
} from "./serialization";
export type {
  AnimationCapability,
  AnimationCategory,
  AnimationConfiguration,
  AnimationConfigurationInput,
  AnimationType,
  BringForwardInput,
  CommandResult,
  ConfigureAnimationInput,
  ConfigureTransitionInput,
  ConfirmPresentationPublishedInput,
  ConfirmPresentationSavedInput,
  CreateElementInput,
  CreatePresentationDeletionIntentResult,
  CreatePresentationInput,
  CreatePresentationResult,
  CreateSlideInput,
  DeleteElementInput,
  DeleteSlideInput,
  DeserializePresentationStateOptions,
  DeserializePresentationStateResult,
  DuplicateElementInput,
  DuplicateSlideInput,
  EditElementInput,
  EditSlideInput,
  ElementPatch,
  ElementPosition,
  ElementSize,
  EntityRevisionTransition,
  HistoryCommandInput,
  ImageElement,
  ImageStyle,
  ImageStylePatch,
  MoveElementInput,
  NewPresentationElement,
  OperationSource,
  PresentationCanvas,
  PresentationCoreError,
  PresentationCoreErrorCode,
  PresentationDeletionIntent,
  PresentationDocumentState,
  PresentationElement,
  PresentationLifecycle,
  PresentationOperation,
  PresentationSnapshotIntegrityStatus,
  PresentationSnapshotReceiptVerificationInput,
  PresentationState,
  PresentationStatus,
  RenamePresentationInput,
  ReorderElementInput,
  ReorderSlideInput,
  ReplaceAssetInput,
  ResizeElementInput,
  SendBackwardInput,
  SerializePresentationStateResult,
  ShapeElement,
  ShapeStyle,
  ShapeStylePatch,
  Slide,
  SlideBackground,
  SlidePatch,
  SlideTransition,
  TextElement,
  TextStyle,
  TextStylePatch,
  TransitionCapability,
  TransitionConfigurationInput,
  TransitionType,
  VerifyPresentationSnapshotReceipt,
} from "./types";
export { PRESENTATION_CANVAS } from "./types";
